#!/bin/bash

apt update
apt upgrade
apt install -y nginx python3  python3-pip  git vim curl 
apt install -y libpq-dev python3-dev
pip3 install -r requirements.txt
python3 manage.py collectstatic
python3 manage.py migrate
service nginx start
cd /etc/nginx/sites-available
vim ksroido.moe

#server {
#  charset utf-8;
#  listen 80;
#  server_name www.ksroido.moe; 
#  location /static {
#    alias /www/sites/ksroido.moe/django22/staticfiles;
#  }
#  location / {
#    proxy_set_header Host $host;
#    rewrite .* /article/article-list permanent;
#    proxy_pass http://unix:/tmp/www.ksroido.moe.socket; 
#  }
#}
ln -s /etc/nginx/sites-available/ksroido.moe /etc/nginx/sites-enabled
pip3 install gunicorn
service nginx reload

#gunicorn --bind unix:/tmp/www.ksroido.moe.socket my_blog.wsgi:application


# save below to /etc/systemd/system/my_blog.service
# [Unit]
# Description=My blog service

# [Service]
# Type=forking
# ExecStart=gunicorn --bind unix:/tmp/www.ksroido.moe.socket /www/sites/ksroido.moe/django22//my_blog.wsgi:application
# KillMode=process
# Restart=on-failure
# RestartSec=5s

# [Install]
# WantedBy=multi-user.target


# systemctl enable my_blog