#!/bin/bash

apt update
apt upgrade
apt install -y nginx python3  python3-pip  git vim curl 
apt install -y libpq-dev python3-dev
pip3 install -r requirements.txt
python3 manage.py collectstatic
python3 manage.py migrate
service nginx start
cd /etc/nginx/sites-available
vim ksroido.moe

#server {
#  charset utf-8;
#  listen 80;
#  server_name www.ksroido.moe; 
#  location /static {
#    alias /www/sites/ksroido.moe/django22/staticfiles;
#  }
#  location / {
#    proxy_set_header Host $host;
#    rewrite .* /article/article-list permanent;
#    proxy_pass http://unix:/tmp/www.ksroido.moe.socket; 
#  }
#}
ln -s /etc/nginx/sites-available/ksroido.moe /etc/nginx/sites-enabled
pip3 install gunicorn
service nginx reload

#gunicorn --bind unix:/tmp/www.ksroido.moe.socket my_blog.wsgi:application

# not work for docker 
# save below to /etc/systemd/system/my_blog.service

# [Unit]
# Description=My blog service

# [Service]
# Type=forking
# WorkingDirectory=/www/sites/ksroido.moe/django22/
# ExecStart=gunicorn --bind unix:/tmp/www.ksroido.moe.socket my_blog.wsgi:application
# KillMode=process
# Restart=on-failure
# RestartSec=5s

# [Install]
# WantedBy=multi-user.target


# systemctl enable my_blog

# docker use below

# echo_supervisord_conf > /etc/supervisord.conf
# mkdir /etc/supervisor.d
# vim /etc/supervisord.conf
# add below:
# [include]
# files = supervisor.d/*.ini

# vim /etc/supervisor.d/my_blog.ini

# [program:myblog]
# command=gunicorn --bind unix:/tmp/www.ksroido.moe.socket my_blog.wsgi:application         
# directory=/www/sites/ksroido.moe/django22/       
# redirect_stderr=true          
# stdout_logfile=/www/sites/ksroido.moe/supervisor.log     

chmod -R 755 /www/sites/ksroido.moe/django22/  
chmod 755 /www/sites/ksroido.moe/supervisor.log
useradd blog
